// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgrenciMvc.Database;

namespace OgrenciMvc.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("OgrenciMvc.Models.Bolum", b =>
                {
                    b.Property<int>("BolumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BolumAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BolumBaskani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BolumMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BolumWebSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FakulteId")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BolumId");

                    b.HasIndex("FakulteId");

                    b.ToTable("Bolumler");
                });

            modelBuilder.Entity("OgrenciMvc.Models.Fakulte", b =>
                {
                    b.Property<int>("FakulteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FakulteAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FakulteId");

                    b.ToTable("Fakulteler");
                });

            modelBuilder.Entity("OgrenciMvc.Models.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoyAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StajBelgeleriId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgrenciId");

                    b.HasIndex("BolumId");

                    b.HasIndex("StajBelgeleriId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("OgrenciMvc.Models.StajBelgeleri", b =>
                {
                    b.Property<int>("StajBelgeleriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DosyaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosyaIcerigi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosyaTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgrenciNumara")
                        .HasColumnType("int");

                    b.HasKey("StajBelgeleriId");

                    b.ToTable("StajBelgeleris");
                });

            modelBuilder.Entity("OgrenciMvc.Models.Bolum", b =>
                {
                    b.HasOne("OgrenciMvc.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("OgrenciMvc.Models.Ogrenci", b =>
                {
                    b.HasOne("OgrenciMvc.Models.Bolum", "Bolum")
                        .WithMany()
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgrenciMvc.Models.StajBelgeleri", "StajBelgeleri")
                        .WithMany()
                        .HasForeignKey("StajBelgeleriId");

                    b.Navigation("Bolum");

                    b.Navigation("StajBelgeleri");
                });
#pragma warning restore 612, 618
        }
    }
}
